services:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk-webhook-server:latest
    container_name: immich-kiosk-webhook-server
    env_file:
      - .env
    environment:
      LANG: "en_GB"
      TZ: "Europe/London"
    ports:
      - 6000:6000
    restart: always
